// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eduardo.OpenAISmartTest
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string OpenAISmartTestString = "a8eb0343-b35c-4175-95d8-50549e609ff3";
        public static Guid OpenAISmartTest = new Guid(OpenAISmartTestString);

        public const string guidOpenAISmartTestPackageCmdSetString = "8b0b1a54-4655-4dae-8984-022f82a739f2";
        public static Guid guidOpenAISmartTestPackageCmdSet = new Guid(guidOpenAISmartTestPackageCmdSetString);

        public const string OpenAISmartTestCompleteIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eea";
        public static Guid OpenAISmartTestCompleteIcon = new Guid(OpenAISmartTestCompleteIconString);

        public const string OpenAISmartTestAddTestsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eeb";
        public static Guid OpenAISmartTestAddTestsIcon = new Guid(OpenAISmartTestAddTestsIconString);

        public const string OpenAISmartTestFindBugsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eec";
        public static Guid OpenAISmartTestFindBugsIcon = new Guid(OpenAISmartTestFindBugsIconString);

        public const string OpenAISmartTestOptimizeIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eed";
        public static Guid OpenAISmartTestOptimizeIcon = new Guid(OpenAISmartTestOptimizeIconString);

        public const string OpenAISmartTestExplainIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eee";
        public static Guid OpenAISmartTestExplainIcon = new Guid(OpenAISmartTestExplainIconString);

        public const string OpenAISmartTestAddCommentsIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eef";
        public static Guid OpenAISmartTestAddCommentsIcon = new Guid(OpenAISmartTestAddCommentsIconString);

        public const string OpenAISmartTestAddSummaryIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eaa";
        public static Guid OpenAISmartTestAddSummaryIcon = new Guid(OpenAISmartTestAddSummaryIconString);

        public const string OpenAISmartTestAddSummaryForAllIconString = "2de8036f-824c-4b98-bf28-0805ccce17f4";
        public static Guid OpenAISmartTestAddSummaryForAllIcon = new Guid(OpenAISmartTestAddSummaryForAllIconString);

        public const string OpenAISmartTestAskAnythingIconString = "c12a8ed0-fbe5-4815-a3fb-2cb73ab06eba";
        public static Guid OpenAISmartTestAskAnythingIcon = new Guid(OpenAISmartTestAskAnythingIconString);

        public const string OpenAISmartTestChatGPTIconString = "4c9af432-30b5-44cb-9a6e-3121c6dc7a49";
        public static Guid OpenAISmartTestChatGPTIcon = new Guid(OpenAISmartTestChatGPTIconString);

        public const string OpenAISmartTestTurboIconString = "4c9af432-30b5-44cb-9a6e-3121c6dc7a50";
        public static Guid OpenAISmartTestTurboIcon = new Guid(OpenAISmartTestTurboIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyGroupForSubMenu = 0x1000;
        public const int MyGroupForCommands = 0x1001;
        public const int MySubMenu = 0x2000;
        public const int Complete = 0x0000;
        public const int AddTests = 0x0100;
        public const int FindBugs = 0x0200;
        public const int Optimize = 0x0300;
        public const int Explain = 0x0400;
        public const int AddComments = 0x0500;
        public const int AddSummary = 0x0600;
        public const int AddSummaryForAll = 0x0700;
        public const int AskAnything = 0x0800;
        public const int cmdidTerminalWindowCommand = 0x0100;
        public const int cmdidTerminalWindowTurboCommand = 0x0101;
        public const int completeIcon = 0x0001;
        public const int addTestsIcon = 0x0001;
        public const int findBugsIcon = 0x0001;
        public const int optimizeIcon = 0x0001;
        public const int explainIcon = 0x0001;
        public const int addCommentsIcon = 0x0001;
        public const int addSummaryIcon = 0x0001;
        public const int addSummaryForAllIcon = 0x0001;
        public const int askAnythingIcon = 0x0001;
        public const int chatGPTIcon = 0x0001;
        public const int turboIcon = 0x0001;
    }
}