// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Eduardo.OpenAISmartTest
{
    internal sealed partial class Vsix
    {
        public const string Id = "OpenAISmartTest2019.4854bc91-135d-4672-a0cf-70464b50ze9e";
        public const string Name = "OpenAI Smart Test";
        public const string Description = @"Comandos invocados no OpenAI, basta selecionar o o método completo clicar direito com mouse e selecione Smart Test Comandos e então abrirá opções desejadas para execução.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "My Prototypes";
        public const string Tags = "Test, QA";
    }
}
